### ISSUE TITLE
Package pixi-pack itself?

### ISSUE THREAD

**Issue by royfrancis** [Quantco/pixi-pack#54]
I need to move pixi environments to a system without internet. Copying `.pixi/envs` doesn't seem to work. Then I came across pixi-pack. But pixi-pack itself is an environment. The pixi binary was easy to copy. But, I am not quite sure how to get pixi-pack on to a system without internet.

**Comment by pavelzw** [comment]
You can download pixi-pack from the releases page https://github.com/Quantco/pixi-pack/releases/tag/v0.1.8

**Comment by royfrancis** [comment]
It takes in a pixi environment and spits out a conda environment which was weird. But manually changing the folder structure and copying over the pixi.lock and pixi.toml eventually made it work.
