### ISSUE TITLE
Clickable self-extract

### ISSUE THREAD

**Issue by maurosilber** [Quantco/pixi-pack#83]
Running `pixi-pack pack --create-executable` creates a self-contained script that unpacks the environment when it is run.

On MacOS, if we change the extension from `.sh` to `.command`, it can be executed by double-clicking the script in Finder (otherwise, it is opened by an editor, at least in my case).

Also, it would be needed to change to the script's directory: 
```sh
# Change to script's directory
cd -- "$(dirname "$0")"
```
Otherwise it is extracted in the home directory.

Would you be interested in adding this behaviour to `pixi-pack`? I wouldn't mind creating a pull request.

*Motivation:* I was trying to create an installer for a GUI app for non-technical users, that they could "install" by double-clicking it. It will not be enough with this change, but is a step in that direction.

**Comment by pavelzw** [comment]
hmm, i personally feel like this is a bit too specific.
also, when providing this kind of feature, we should ensure this works on Linux and Windows as well.

also, adding something like this would result in people not being able to call the executable from another directory...

I think it would be easiest if you just add this line to your CI pipeline that builds the binary

```bash
pixi-pack pack --create-executable -o environment.command
gsed -i '2i\cd -- "$(dirname "$0")"' environment.command
```
